version: '3.1'

services:

  db:
    image: postgres
    container_name: internetdata
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    env_file: .venv
   
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080


  
  

